name: dart_pretty_print
description: Simple dart package to print colorful texts to console
version: 1.0.0
repository: https://github.com/ankiimation/dart_pretty_print

environment:
  sdk: '>=2.12.0 <4.0.0'

# Add regular dependencies here.
# dependencies:
#   # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
